export enum TipoBoleto {
  ARRECADACAO_PREFEITURA = 'ARRECADACAO_PREFEITURA',
  CONVENIO_SANEAMENTO = 'CONVENIO_SANEAMENTO',
  CONVENIO_ENERGIA_ELETRICA_E_GAS = 'CONVENIO_ENERGIA_ELETRICA_E_GAS',
  CONVENIO_TELECOMUNICACOES = 'CONVENIO_TELECOMUNICACOES',
  ARRECADACAO_ORGAOS_GOVERNAMENTAIS = 'ARRECADACAO_ORGAOS_GOVERNAMENTAIS',
  ARRECADACAO_TAXAS_DE_TRANSITO = 'ARRECADACAO_TAXAS_DE_TRANSITO',
  BANCO = 'BANCO',
  OUTROS = 'OUTROS'
}
